DATA_RAW <- "data/raw/LungData.xlsx"
DATA_PROCESSED <- "data/processed/lung_clean.rds"
OUTPUT_TABLES <- "output/tables"
OUTPUT_FIGURES <- "output/figures"
MODEL_PATH <- "models/logistic_final.rds"
LOG_PATH <- "logs"

RANDOM_SEED <- 42
TEST_SIZE <- 0.2
TARGET <- "MORTALITY_30D"

FEATURE_SET <- Sys.getenv("FEATURE_SET", unset = "preop_min")

CATEGORICAL_FEATURES_PREOP_MIN <- c(
  "Age_Group", "SEX", "Race",
  "BMI_Group",
  "DIABETES", "SMOKE", "ETOH",
  "DYSPNEA", "DNR", "FNCTSTATUS",
  "HXCOPD", "ASCITES", "ESOVAR",
  "HXCHF", "HXMI", "PRVPCI", "PRVPCS", "HXANGINA", "HYPERMED",
  "HXPVD", "RESTPAIN",
  "RENAFAIL", "DIALYSIS",
  "IMPSENS", "COMA", "HEMI",
  "HXTIA", "CVA", "CVANO", "TUMORCNS", "Para", "QUAD",
  "DISCANCR",
  "STEROID", "WTLOSS", "BLEEDDIS", "TRANSFUS",
  "CHEMO", "RADIO",
  "Leukocytosis", "Anemia",
  "ASACLAS"
)

NUMERICAL_FEATURES_PREOP_MIN <- c(
  "Age", "HEIGHT", "WEIGHT", "BMI", "PACKS",
  "PRSODM",
  "PRBUN", "PRCREAT", "PRALBUM", "PRBILI", "PRSGOT", "PRALKPH",
  "PRWBC", "PRHCT", "PRPLATE", "PRPTT", "PRINR", "RBC"
)

CATEGORICAL_FEATURES_PREOP_WIDE <- c(
  "Open vs VATS", "Resection", "TRANST",
  "Age_Group", "SEX", "Race", "ANESTHES", "ATTEND", "Attend vs Resident",
  "Thoracic Surgeon", "SURGSPEC", "BMI_Group", "DIABETES", "SMOKE", "ETOH",
  "DYSPNEA", "DNR", "FNCTSTATUS", "VENTILAT", "HXCOPD", "CPNEUMON", "ASCITES",
  "ESOVAR", "HXCHF", "HXMI", "PRVPCI", "PRVPCS", "HXANGINA", "HYPERMED",
  "HXPVD", "RESTPAIN", "RENAFAIL", "DIALYSIS", "IMPSENS", "COMA", "HEMI",
  "HXTIA", "CVA", "CVANO", "TUMORCNS", "Para", "QUAD", "DISCANCR", "WNDINF",
  "STEROID", "WTLOSS", "BLEEDDIS", "TRANSFUS", "CHEMO", "RADIO", "PrOper30",
  "Leukocytosis", "Anemia", "WNDCLAS", "ASACLAS"
)

NUMERICAL_FEATURES_PREOP_WIDE <- c(
  "WORKRVU", "Age", "HEIGHT", "WEIGHT", "BMI", "PACKS",
  "PRSODM", "PRBUN", "PRCREAT", "PRALBUM", "PRBILI", "PRSGOT", "PRALKPH",
  "PRWBC", "PRHCT", "PRPLATE", "PRPTT", "PRINR", "PGY", "RBC", "ANESURG",
  "SURGANE", "DPATRM", "ANETIME", "OPTIME"
)

if (FEATURE_SET == "preop_min") {
  CATEGORICAL_FEATURES <- CATEGORICAL_FEATURES_PREOP_MIN
  NUMERICAL_FEATURES <- NUMERICAL_FEATURES_PREOP_MIN
} else if (FEATURE_SET == "preop_wide") {
  CATEGORICAL_FEATURES <- CATEGORICAL_FEATURES_PREOP_WIDE
  NUMERICAL_FEATURES <- NUMERICAL_FEATURES_PREOP_WIDE
} else {
  stop("Unknown FEATURE_SET: ", FEATURE_SET)
}
